"Agents Choose"
{
	"preview"					"1"		// Давать ли возможность игрокам включать вид от 3-ого лица?
	"preview_block_transmits"	"1"		// Блокировать ли отправку пакетов о других игроках при осмотре агентов, чтобы их не было видно? Поставьте этот плагин для отключеения радара - https://hlmod.ru/threads/hide-menu-blockers.51015/#post-445369
	"forcibly_set_model"		"1"		// Сразу ли устанавливать модель агента на игрока при его выборе? При 0 агент будет установлен при следующем спавне игрока.
	"hide_no_access_agents"		"0"		// Скрывает пункт в меню с агентом, если один из модулей ограничил доступ к нему.

	"agents"
	{
		// DefIndex агентов.
		"4619"
		{
			"name"		"'Blueberries' Buckshot | NSWC SEAL"		// Название агента. Опцианально с файлом перевода.
			"team"		"ct"								// Команда для которой будет доступен агент.
		}
		"4680"
		{
			"name"		"'Two Times' McCoy | TACP Cavalry"
			"team"		"ct"
		}
		"5106"
		{
			"name"		"Osiris | Elite Crew"
			"team"		"t"
		}
		"5107"
		{
			"name"		"Prof. Shahmat | Elite Crew"
			"team"		"t"
		}
		"5108"
		{
			"name"		"The Elite Mr. Muhlik | Elite Crew"
			"team"		"t"
		}
		"5205"
		{
			"name"		"Soldier | Phoenix"
			"team"		"t"
		}
		"5206"
		{
			"name"		"Enforcer | Phoenix"
			"team"		"t"
		}
		"5207"
		{
			"name"		"Slingshot | Phoenix"
			"team"		"t"
		}
		"5305"
		{
			"name"		"Operator | FBI SWAT"
			"team"		"ct"
		}
		"5306"
		{
			"name"		"Markus Delrow | FBI HRT"
			"team"		"ct"
		}
		"5307"
		{
			"name"		"Michael Syfers | FBI Sniper"
			"team"		"ct"
		}
		"5308"
		{
			"name"		"Special Agent Ava | FBI"
			"team"		"ct"
		}
		"5400"
		{
			"name"		"3rd Commando Company | KSK"
			"team"		"ct"
		}
		"5401"
		{
			"name"		"Seal Team 6 Soldier | NSWC SEAL"
			"team"		"ct"
		}
		"5402"
		{
			"name"		"Buckshot | NSWC SEAL"
			"team"		"ct"
		}
		"5403"
		{
			"name"		"'Two Times' McCoy | USAF TACP"
			"team"		"ct"
		}
		"5404"
		{
			"name"		"Lt. Commander Ricksaw | NSWC SEAL"
			"team"		"ct"
		}
		"5500"
		{
			"name"		"Dragomir | Sabre"
			"team"		"t"
		}
		"5501"
		{
			"name"		"Maximus | Sabre"
			"team"		"t"
		}
		"5502"
		{
			"name"		"Rezan The Ready | Sabre"
			"team"		"t"
		}
		"5503"
		{
			"name"		"Blackwolf | Sabre"
			"team"		"t"
		}
		"5504"
		{
			"name"		"'The Doctor' Romanov | Sabre"
			"team"		"t"
		}
		"5505"
		{
			"name"		"Dragomir | Sabre Footsoldier"
			"team"		"t"
		}
		"5601"
		{
			"name"		"B Squadron Officer | SAS"
			"team"		"ct"
		}
		"4711"
		{
			"name"		"Cmdr. Mae 'Dead Cold' Jamison | SWAT"
			"team"		"ct"
		}
		"4712"
		{
			"name"		"1st Lieutenant Farlow | SWAT"
			"team"		"ct"
		}
		"4713"
		{
			"name"		"John 'Van Healen' Kask | SWAT"
			"team"		"ct"
		}
		"4714"
		{
			"name"		"Bio-Haz Specialist | SWAT"
			"team"		"ct"
		}
		"4715"
		{
			"name"		"Sergeant Bombson | SWAT"
			"team"		"ct"
		}
		"4716"
		{
			"name"		"Chem-Haz Specialist | SWAT"
			"team"		"ct"
		}
		"4718"
		{
			"name"		"Rezan the Redshirt | Sabre"
			"team"		"t"
		}
		"4726"
		{
			"name"		"Sir Bloody Miami Darryl | The Professionals"
			"team"		"t"
		}
		"4727"
		{
			"name"		"Safecracker Voltzmann | The Professionals"
			"team"		"t"
		}
		"4728"
		{
			"name"		"Little Kev | The Professionals"
			"team"		"t"
		}
		"4730"
		{
			"name"		"Getaway Sally | The Professionals"
			"team"		"t"
		}
		"4732"
		{
			"name"		"Number K | The Professionals"
			"team"		"t"
		}
		"4733"
		{
			"name"		"Sir Bloody Silent Darryl | The Professionals"
			"team"		"t"
		}
		"4734"
		{
			"name"		"Sir Bloody Skullhead Darryl | The Professionals"
			"team"		"t"
		}
		"4735"
		{
			"name"		"Sir Bloody Darryl Royale | The Professionals"
			"team"		"t"
		}
		"4736"
		{
			"name"		"Sir Bloody Loudmouth Darryl | The Professionals"
			"team"		"t"
		}
	}

	"patchs"
	{
		// "AttrIndex нашивки"		"Название нашивки. Опцианально с файлом перевода."
		"4550"		"Crazy Banana"
		"4551"		"The Boss"
		"4552"		"Chicken Lover"
		"4553"		"Welcome to the Clutch"
		"4554"		"Dragon"
		"4555"		"Easy Peasy"
		"4556"		"Rage"
		"4557"		"Howl"
		"4558"		"Koi"
		"4559"		"Longevity"
		"4560"		"Wildfire"
		"4561"		"Vigilance"
		"4562"		"Bloodhound"
		"4563"		"Bravo"
		"4564"		"Breakout"
		"4565"		"Danger Zone"
		"4566"		"Hydra"
		"4567"		"Payback"
		"4568"		"Phoenix"
		"4569"		"Shattered Web"
		"4570"		"Vanguard"
		"4571"		"Metal Silver"
		"4572"		"Metal Gold Nova I"
		"4575"		"Metal Gold Nova Master"
		"4576"		"Metal Master Guardian I"
		"4578"		"Metal Master Guardian Elite"
		"4579"		"Metal Distinguished Master Guardian"
		"4580"		"Metal Legendary Eagle"
		"4581"		"Metal Legendary Eagle Master"
		"4582"		"Metal Supreme Master First Class"
		"4583"		"Metal The Global Elite"
		"4584"		"Metal Distinguished Master Guardian"
		"4585"		"Metal Legendary Eagle"
		"4586"		"Metal Legendary Eagle Master"
		"4587"		"Silver Demon"
		"4588"		"Supreme Master"
		"4589"		"Alyx"
		"4591"		"Sustenance!"
		"4592"		"Vortigaunt"
		"4593"		"Headcrab Glyph"
		"4594"		"Copper Lambda"
		"4595"		"Health"
		"4596"		"Combine Helmet"
		"4597"		"Black Mesa"
		"4598"		"CMB"
		"4599"		"Lambda"
		"4600"		"City 17"
		"4697"		"Metal The Global Elite"
		"4699"		"Metal Master Guardian I"
		"4700"		"Metal Gold Nova IV"
	}
}